# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Profile.create(firstname: "Nancy",
                middlename:"",
                middlename2: "",
                lastname: "Burke",
                fullname: "Nancy Burke",
                profile_type: "Research Team Member",
                en_project_title: "Co-investigator",
                en_affiliation: "UC San Francisco, UC Merced",
                en_bio: "",
                zh_tw_project_title: "",
                zh_tw_affiliation: "",
                zh_tw_bio: "",
                zh_cn_project_title: "",
                zh_cn_affiliation: "",
                zh_cn_bio: "",
                vi_project_title: "",
                vi_affiliation: "",
                vi_bio: "",
                hmn_project_title: "",
                hmn_affiliation: "",
                hmn_bio: "",
                external_links: "https://www.ucmerced.edu/content/nancy-burke")

Profile.create(firstname: "Joyce",
                middlename:"",
                middlename2: "",
                lastname: "Cheng",
                fullname: "Joyce Cheng",
                profile_type: "Research Team Member",
                en_project_title: "Executive Director",
                en_affiliation: "Chinese Community Health Resource Center",
                en_bio: "",
                zh_tw_project_title: "",
                zh_tw_affiliation: "",
                zh_tw_bio: "",
                zh_cn_project_title: "",
                zh_cn_affiliation: "",
                zh_cn_bio: "",
                vi_project_title: "",
                vi_affiliation: "",
                vi_bio: "",
                hmn_project_title: "",
                hmn_affiliation: "",
                hmn_bio: "",
                external_links: "https://www.cchrchealth.org/")


Profile.create(firstname: "Rianna",
                middlename:"",
                middlename2: "",
                lastname: "Garcia",
                fullname: "Rianna Garcia",
                profile_type: "Research Team Member",
                en_project_title: "Student Intern",
                en_affiliation: "San Jose State University",
                en_bio: "",
                zh_tw_project_title: "",
                zh_tw_affiliation: "",
                zh_tw_bio: "",
                zh_cn_project_title: "",
                zh_cn_affiliation: "",
                zh_cn_bio: "",
                vi_project_title: "",
                vi_affiliation: "",
                vi_bio: "",
                hmn_project_title: "",
                hmn_affiliation: "",
                hmn_bio: "",
                external_links: "")


Profile.create(firstname: "Minji",
                middlename:"",
                middlename2: "",
                lastname: "Kim",
                fullname: "Minji Kim",
                profile_type: "Research Team Member",
                en_project_title: "Co-investigator",
                en_affiliation: "UC San Francisco",
                en_bio: "",
                zh_tw_project_title: "",
                zh_tw_affiliation: "",
                zh_tw_bio: "",
                zh_cn_project_title: "",
                zh_cn_affiliation: "",
                zh_cn_bio: "",
                vi_project_title: "",
                vi_affiliation: "",
                vi_bio: "",
                hmn_project_title: "",
                hmn_affiliation: "",
                hmn_bio: "",
                external_links: "https://profiles.ucsf.edu/minji.kim")


Profile.create(firstname: "Nikita",
                middlename:"",
                middlename2: "",
                lastname: "Madan",
                fullname: "Nikita Madan",
                profile_type: "Research Team Member",
                en_project_title: "Student Intern",
                en_affiliation: "San Jose State University",
                en_bio: "",
                zh_tw_project_title: "",
                zh_tw_affiliation: "",
                zh_tw_bio: "",
                zh_cn_project_title: "",
                zh_cn_affiliation: "",
                zh_cn_bio: "",
                vi_project_title: "",
                vi_affiliation: "",
                vi_bio: "",
                hmn_project_title: "",
                hmn_affiliation: "",
                hmn_bio: "",
                external_links: "")


Profile.create(firstname: "Tung",
                middlename:"",
                middlename2: "",
                lastname: "Nguyen",
                fullname: "Tung Nguyen",
                profile_type: "Research Team Member",
                en_project_title: "Co-investigator",
                en_affiliation: "UC San Francisco",
                en_bio: "",
                zh_tw_project_title: "",
                zh_tw_affiliation: "",
                zh_tw_bio: "",
                zh_cn_project_title: "",
                zh_cn_affiliation: "",
                zh_cn_bio: "",
                vi_project_title: "",
                vi_affiliation: "",
                vi_bio: "",
                hmn_project_title: "",
                hmn_affiliation: "",
                hmn_bio: "",
                external_links: "https://profiles.ucsf.edu/tung.nguyen")


Profile.create(firstname: "Susan",
                middlename:"",
                middlename2: "",
                lastname: "Stewart",
                fullname: "Susan Stewart",
                profile_type: "Research Team Member",
                en_project_title: "Co-investigator",
                en_affiliation: "UC Davis",
                en_bio: "",
                zh_tw_project_title: "",
                zh_tw_affiliation: "",
                zh_tw_bio: "",
                zh_cn_project_title: "",
                zh_cn_affiliation: "",
                zh_cn_bio: "",
                vi_project_title: "",
                vi_affiliation: "",
                vi_bio: "",
                hmn_project_title: "",
                hmn_affiliation: "",
                hmn_bio: "",
                external_links: "https://profiles.ucdavis.edu/susan.stewart")


Profile.create(firstname: "Janice",
                middlename:"",
                middlename2: "",
                lastname: "Tsoh",
                fullname: "Janice Tsoh",
                profile_type: "Research Team Member",
                en_project_title: "Principal Investigator",
                en_affiliation: "UC San Francisco",
                en_bio: "",
                zh_tw_project_title: "",
                zh_tw_affiliation: "",
                zh_tw_bio: "",
                zh_cn_project_title: "",
                zh_cn_affiliation: "",
                zh_cn_bio: "",
                vi_project_title: "",
                vi_affiliation: "",
                vi_bio: "",
                hmn_project_title: "",
                hmn_affiliation: "",
                hmn_bio: "",
                external_links: "https://profiles.ucsf.edu/janice.tsoh")


Profile.create(firstname: "Ching",
                middlename:"",
                middlename2: "",
                lastname: "Wong",
                fullname: "Ching Wong",
                profile_type: "Reseacher",
                en_project_title: "Research Staff",
                en_affiliation: "UC San Francisco",
                en_bio: "",
                zh_tw_project_title: "",
                zh_tw_affiliation: "",
                zh_tw_bio: "",
                zh_cn_project_title: "",
                zh_cn_affiliation: "",
                zh_cn_bio: "",
                vi_project_title: "",
                vi_affiliation: "",
                vi_bio: "",
                hmn_project_title: "",
                hmn_affiliation: "",
                hmn_bio: "",
                external_links: "")


Profile.create(firstname: "Alan",
                middlename:"",
                middlename2: "",
                lastname: "Wu",
                fullname: "Alan Wu",
                profile_type: "Research Team Member",
                en_project_title: "Co-investigator",
                en_affiliation: "UC San Francisco",
                en_bio: "",
                zh_tw_project_title: "",
                zh_tw_affiliation: "",
                zh_tw_bio: "",
                zh_cn_project_title: "",
                zh_cn_affiliation: "",
                zh_cn_bio: "",
                vi_project_title: "",
                vi_affiliation: "",
                vi_bio: "",
                hmn_project_title: "",
                hmn_affiliation: "",
                hmn_bio: "",
                external_links: "https://profiles.ucsf.edu/alan.wu")


Profile.create(firstname: "Kara",
                middlename:"",
                middlename2: "",
                lastname: "Young",
                fullname: "Kara Young",
                profile_type: "Research Team Member",
                en_project_title: "Community Coordinator",
                en_affiliation: "Chinese Community Health Resource Center",
                en_bio: "",
                zh_tw_project_title: "",
                zh_tw_affiliation: "",
                zh_tw_bio: "",
                zh_cn_project_title: "",
                zh_cn_affiliation: "",
                zh_cn_bio: "",
                vi_project_title: "",
                vi_affiliation: "",
                vi_bio: "",
                hmn_project_title: "",
                hmn_affiliation: "",
                hmn_bio: "",
                external_links: "https://www.cchrchealth.org/")


Profile.create(firstname: "Edgar",
                middlename:"",
                middlename2: "",
                lastname: "Yu",
                fullname: "Edgar Yu",
                profile_type: "Research Team Member",
                en_project_title: "Study Coordinator",
                en_affiliation: "",
                en_bio: "",
                zh_tw_project_title: "",
                zh_tw_affiliation: "",
                zh_tw_bio: "",
                zh_cn_project_title: "",
                zh_cn_affiliation: "",
                zh_cn_bio: "",
                vi_project_title: "",
                vi_affiliation: "",
                vi_bio: "",
                hmn_project_title: "",
                hmn_affiliation: "",
                hmn_bio: "",
                external_links: "https://profiles.ucsf.edu/edgar.yu")


Profile.create(firstname: "Christy",
                middlename:"",
                middlename2: "",
                lastname: "Calhoun",
                fullname: "Christy Calhoun",
                profile_type: "CAB member",
                en_project_title: "",
                en_affiliation: "Healthwise",
                en_bio: "",
                zh_tw_project_title: "",
                zh_tw_affiliation: "",
                zh_tw_bio: "",
                zh_cn_project_title: "",
                zh_cn_affiliation: "",
                zh_cn_bio: "",
                vi_project_title: "",
                vi_affiliation: "",
                vi_bio: "",
                hmn_project_title: "",
                hmn_affiliation: "",
                hmn_bio: "",
                external_links: "")


Profile.create(firstname: "Eunice",
                middlename:"",
                middlename2: "",
                lastname: "Cheng",
                fullname: "Eunice Cheng",
                profile_type: "CAB member",
                en_project_title: "",
                en_affiliation: "Asian Americans for Community Involvement",
                en_bio: "",
                zh_tw_project_title: "",
                zh_tw_affiliation: "",
                zh_tw_bio: "",
                zh_cn_project_title: "",
                zh_cn_affiliation: "",
                zh_cn_bio: "",
                vi_project_title: "",
                vi_affiliation: "",
                vi_bio: "",
                hmn_project_title: "",
                hmn_affiliation: "",
                hmn_bio: "",
                external_links: "")


Profile.create(firstname: "Mina",
                middlename:"",
                middlename2: "",
                lastname: "Li",
                fullname: "Mina Li",
                profile_type: "CAB member",
                en_project_title: "",
                en_affiliation: "KTSF Channel 26",
                en_bio: "",
                zh_tw_project_title: "",
                zh_tw_affiliation: "",
                zh_tw_bio: "",
                zh_cn_project_title: "",
                zh_cn_affiliation: "",
                zh_cn_bio: "",
                vi_project_title: "",
                vi_affiliation: "",
                vi_bio: "",
                hmn_project_title: "",
                hmn_affiliation: "",
                hmn_bio: "",
                external_links: "")


Profile.create(firstname: "Haley",
                middlename:"",
                middlename2: "",
                lastname: "Mullins",
                fullname: "Haley Mullins",
                profile_type: "CAB member",
                en_project_title: "",
                en_affiliation: "Healthwise",
                en_bio: "",
                zh_tw_project_title: "",
                zh_tw_affiliation: "",
                zh_tw_bio: "",
                zh_cn_project_title: "",
                zh_cn_affiliation: "",
                zh_cn_bio: "",
                vi_project_title: "",
                vi_affiliation: "",
                vi_bio: "",
                hmn_project_title: "",
                hmn_affiliation: "",
                hmn_bio: "",
                external_links: "")


Profile.create(firstname: "Fiona",
                middlename:"",
                middlename2: "",
                lastname: "Ng",
                fullname: "Fiona Ng",
                profile_type: "CAB member",
                en_project_title: "",
                en_affiliation: "UC San Francisco",
                en_bio: "",
                zh_tw_project_title: "",
                zh_tw_affiliation: "",
                zh_tw_bio: "",
                zh_cn_project_title: "",
                zh_cn_affiliation: "",
                zh_cn_bio: "",
                vi_project_title: "",
                vi_affiliation: "",
                vi_bio: "",
                hmn_project_title: "",
                hmn_affiliation: "",
                hmn_bio: "",
                external_links: "")


Profile.create(firstname: "Tony",
                middlename:"",
                middlename2: "",
                lastname: "Nguyen",
                fullname: "Tony Nguyen",
                profile_type: "CAB member",
                en_project_title: "",
                en_affiliation: "California Healthy Nail Salon Collaborative",
                en_bio: "",
                zh_tw_project_title: "",
                zh_tw_affiliation: "",
                zh_tw_bio: "",
                zh_cn_project_title: "",
                zh_cn_affiliation: "",
                zh_cn_bio: "",
                vi_project_title: "",
                vi_affiliation: "",
                vi_bio: "",
                hmn_project_title: "",
                hmn_affiliation: "",
                hmn_bio: "",
                external_links: "")


Profile.create(firstname: "Marta",
                middlename:"",
                middlename2: "",
                lastname: "Sylvia",
                fullname: "Marta Sylvia",
                profile_type: "CAB member",
                en_project_title: "",
                en_affiliation: "Healthwise",
                en_bio: "",
                zh_tw_project_title: "",
                zh_tw_affiliation: "",
                zh_tw_bio: "",
                zh_cn_project_title: "",
                zh_cn_affiliation: "",
                zh_cn_bio: "",
                vi_project_title: "",
                vi_affiliation: "",
                vi_bio: "",
                hmn_project_title: "",
                hmn_affiliation: "",
                hmn_bio: "",
                external_links: "")


Profile.create(firstname: "Jennifer",
                middlename:"",
                middlename2: "",
                lastname: "Xiong",
                fullname: "Jennier Xiong",
                profile_type: "CAB member",
                en_project_title: "",
                en_affiliation: "Hlob Hmong Center",
                en_bio: "",
                zh_tw_project_title: "",
                zh_tw_affiliation: "",
                zh_tw_bio: "",
                zh_cn_project_title: "",
                zh_cn_affiliation: "",
                zh_cn_bio: "",
                vi_project_title: "",
                vi_affiliation: "",
                vi_bio: "",
                hmn_project_title: "",
                hmn_affiliation: "",
                hmn_bio: "",
                external_links: "")
